$schema: https://moonrepo.dev/schemas/tasks.json
fileGroups:
  assets:
  - assets/**/*
  sources:
  - src/**/*
  tsup-config:
  - tsup.config.ts
  tsup-dist:
  - ./target/tsup/dist/**/*
tasks:
  mcp-inspector:
    toolchain: node
    preset: server
    deps:
    - build
    script: |
      DANGEROUSLY_OMIT_AUTH=true yarn dlx @modelcontextprotocol/inspector --transport stdio -- tsx $projectRoot/target/tsup/dist/main.js
    inputs:
    - '@group(assets)'
    - '@group(sources)'
    - '@group(tsup-config)'
inheritedBy:
  tag: mcp
