$schema: https://moonrepo.dev/schemas/tasks.json
tasks:
  npm-publish:
    options:
      cache: false
      outputStyle: stream
      runInCI: skip
    deps:
    - ~:build
    script: $workspaceRoot/etc/scripts/moon-tasks/npm-publish.ts
    env:
      PROJECT_ROOT: $projectRoot
inheritedBy:
  tag: npm
