name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - release/*.*

jobs:
  build-test:
    name: Build and Test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dagger
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: 0.18.9
          verb: functions
          workdir: ./etc/workflow-runtime

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install

      - run: "yarn install"
      - run: "./etc/scripts/workflows/build-test.ts"
