name: Release Publish Workflow

on:
  push:
    tags:
      - v*.*.*
      - v0.*.*-*

jobs:
  release-publish:
    name: Release Publish Job
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases and uploading assets
      id-token: write  # Required for Trusted Publishing
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Dagger
        uses: dagger/dagger-for-github@v8.2.0
        with:
          version: v0.20.3
          verb: functions
          workdir: ./etc/workflow-runtime

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install

      - run: "./etc/scripts/workflows/release-publish.ts"
        env:
          RELEASE_TAG: ${{ github.ref_name }}
          FIREFOX_API_KEY: ${{ secrets.FIREFOX_API_KEY }}
          FIREFOX_API_SECRET: ${{ secrets.FIREFOX_API_SECRET }}
          # YARN_NPM_AUTH_TOKEN: ${{ secrets.YARN_NPM_AUTH_TOKEN }}

      - name: Upload target directory
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: target-directory
          path: target/
          retention-days: 1

      - name: Upload extensions to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: ${{ startsWith(github.ref_name, 'v0.') }}
          make_latest: false
